# Generated by Django 3.2 on 2021-05-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('fragile', 'Fragile'), ('liquid', 'Liquid'), ('solid', 'Solid')], max_length=100),
        ),
    ]
