# Generated by Django 3.2 on 2021-05-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('percel', '0002_alter_product_product_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='total_weight',
            field=models.FloatField(),
        ),
    ]
